-- Habeeb Kotun Jr.
-- Nashville Software School, DS5
-- February 1, 2022
-- SQL Prescribers

--- Part 1
-- Question 1a
SELECT NPI,
	SUM(TOTAL_CLAIM_COUNT)
FROM PRESCRIPTION
GROUP BY NPI
ORDER BY SUM(TOTAL_CLAIM_COUNT) DESC
LIMIT 1;
-- Answer: Prescriber with NPI 1881634483 had the highest amount of claims at 99707 claims.

-- Question 1b
SELECT P1.NPPES_PROVIDER_FIRST_NAME AS FIRST_NAME,
	P1.NPPES_PROVIDER_LAST_ORG_NAME AS LAST_NAME,
	P1.SPECIALTY_DESCRIPTION AS SPECIALTY,
	SUM(P2.TOTAL_CLAIM_COUNT) AS TOTAL_CLAIMS
FROM PRESCRIBER AS P1
INNER JOIN PRESCRIPTION AS P2 ON P1.NPI = P2.NPI
GROUP BY 1, 2, 3
ORDER BY SUM(P2.TOTAL_CLAIM_COUNT) DESC
LIMIT 1;
-- Answer: Bruce Pendley had the highest amount of claims. His specialty description in the database is listed as Family Practice.

-- Question 2a
SELECT P1.SPECIALTY_DESCRIPTION,
	SUM(P2.TOTAL_CLAIM_COUNT) AS TOTAL_CLAIMS
FROM PRESCRIBER AS P1
INNER JOIN PRESCRIPTION AS P2 ON P1.NPI = P2.NPI
GROUP BY P1.SPECIALTY_DESCRIPTION
ORDER BY TOTAL_CLAIMS DESC
LIMIT 1;
-- Answer: Family Practice is the specialty with the most total number of claims.

-- Question 2b
SELECT P1.SPECIALTY_DESCRIPTION,
	SUM(P2.TOTAL_CLAIM_COUNT) AS TOTAL_CLAIMS
FROM PRESCRIBER AS P1
INNER JOIN PRESCRIPTION AS P2 ON P1.NPI = P2.NPI
INNER JOIN DRUG AS D ON P2.DRUG_NAME = D.DRUG_NAME
WHERE D.OPIOID_DRUG_FLAG = 'Y'
GROUP BY P1.SPECIALTY_DESCRIPTION
ORDER BY TOTAL_CLAIMS DESC
LIMIT 1;
-- Answer: Nurse Practitioner is the specialty with the most total number of claims for opioids.

-- Question 2c
SELECT P1.SPECIALTY_DESCRIPTION,
	COUNT(P2.TOTAL_CLAIM_COUNT) AS NUMBER_PRESCRIPTIONS
FROM PRESCRIBER AS P1
FULL JOIN PRESCRIPTION AS P2 ON P1.NPI = P2.NPI
GROUP BY P1.SPECIALTY_DESCRIPTION
HAVING COUNT(P2.TOTAL_CLAIM_COUNT) = 0 
-- Answer: There are 15 specialties that appear in the prescriber table that have no associated prescriptions in the prescription table.

-- Question 3a
SELECT D.GENERIC_NAME,
	SUM(P.TOTAL_DRUG_COST)::MONEY AS TOTAL_DRUG_COST
FROM PRESCRIPTION AS P
INNER JOIN DRUG AS D ON P.DRUG_NAME = D.DRUG_NAME
GROUP BY D.GENERIC_NAME
ORDER BY SUM(P.TOTAL_DRUG_COST) DESC
LIMIT 1;
-- Answer: Insulin is the drug with the highest total drug cost.

-- Question 3b
SELECT D.GENERIC_NAME,
	SUM(P.TOTAL_DRUG_COST)::MONEY AS TOTAL_DRUG_COST,
	ROUND(SUM(TOTAL_DRUG_COST) / SUM(TOTAL_DAY_SUPPLY),
		2) AS COST_PER_DAY
FROM PRESCRIPTION AS P
INNER JOIN DRUG AS D ON P.DRUG_NAME = D.DRUG_NAME
GROUP BY D.GENERIC_NAME
ORDER BY 3 DESC
LIMIT 1;
-- Answer: C1 Esterase is the drug with the hightest total cost per day.

-- Question 4a
SELECT DRUG_NAME,
	CASE
		WHEN OPIOID_DRUG_FLAG = 'Y' THEN 'opioid'
		WHEN ANTIBIOTIC_DRUG_FLAG = 'Y' THEN 'antibiotic'
		ELSE 'neither'
	END AS DRUG_TYPE
FROM DRUG 

-- Question 4b
SELECT DRUG_TYPE,
	SUM(TOTAL_DRUG_COST)::MONEY
FROM
	(SELECT DRUG_NAME,
			TOTAL_DRUG_COST,
			CASE
				WHEN OPIOID_DRUG_FLAG = 'Y' THEN 'opioid'
				WHEN ANTIBIOTIC_DRUG_FLAG = 'Y' THEN 'antibiotic'
				ELSE 'neither'
			END AS DRUG_TYPE
		FROM DRUG
		FULL JOIN PRESCRIPTION USING (DRUG_NAME)) AS DRUG_BILL
WHERE DRUG_TYPE != 'neither'
GROUP BY DRUG_TYPE
ORDER BY SUM(TOTAL_DRUG_COST) DESC;
-- Answer: More money was spent on opioids.
 
-- Question 5a
SELECT COUNT(DISTINCT CBSA)
FROM CBSA
WHERE CBSANAME LIKE '%, TN%';
-- Answer: There are 10 distinct CBSAs in Tennessee.

-- Question 5b
SELECT CBSA,
	CBSANAME,
	SUM(POPULATION) AS TOTAL_POPULATION
FROM CBSA
INNER JOIN POPULATION USING (FIPSCOUNTY)
GROUP BY CBSA,
	CBSANAME
ORDER BY TOTAL_POPULATION DESC;
/*
Answer: Nashville-Davidson-Murfreesboro-Franklin, TN (CBSA 34980) has the largest combined population.
Morristown, TN (CBSA 34100) has the smallest combined population.
*/ 

-- Question 5c
SELECT COUNTY,
	STATE,
	POPULATION
FROM POPULATION
LEFT JOIN CBSA USING (FIPSCOUNTY)
LEFT JOIN FIPS_COUNTY USING (FIPSCOUNTY)
WHERE CBSA IS NULL
ORDER BY POPULATION DESC;
-- Answer: Sevier county in Tennessee has the largest population that is not included in a CBSA.

-- Question 6a
SELECT DRUG_NAME,
	TOTAL_CLAIM_COUNT
FROM PRESCRIPTION
WHERE TOTAL_CLAIM_COUNT >= 3000
ORDER BY TOTAL_CLAIM_COUNT DESC;

-- Question 6b
SELECT DRUG_NAME,
	TOTAL_CLAIM_COUNT,
	OPIOID_DRUG_FLAG
FROM PRESCRIPTION
LEFT JOIN DRUG USING (DRUG_NAME)
WHERE TOTAL_CLAIM_COUNT >= 3000
ORDER BY TOTAL_CLAIM_COUNT DESC;

-- Question 6c
SELECT DRUG_NAME,
	TOTAL_CLAIM_COUNT,
	OPIOID_DRUG_FLAG,
	NPPES_PROVIDER_FIRST_NAME AS PRESCRIBER_FIRST_NAME,
	NPPES_PROVIDER_LAST_ORG_NAME AS PRESCRIBER_LAST_NAME
FROM PRESCRIPTION
LEFT JOIN DRUG USING (DRUG_NAME)
LEFT JOIN PRESCRIBER USING(NPI)
WHERE TOTAL_CLAIM_COUNT >= 3000
ORDER BY TOTAL_CLAIM_COUNT DESC;

-- Question 7a
SELECT NPI,
	DRUG_NAME
FROM PRESCRIBER
CROSS JOIN DRUG
WHERE SPECIALTY_DESCRIPTION = 'Pain Management'
	AND NPPES_PROVIDER_CITY = 'NASHVILLE'
	AND OPIOID_DRUG_FLAG = 'Y';

-- Question 7b
SELECT NPI,
	DRUG_NAME,
	COALESCE(TOTAL_CLAIM_COUNT, 0) AS TOTAL_CLAIM_COUNT
FROM
	(SELECT NPI,
			DRUG_NAME
		FROM PRESCRIBER
		CROSS JOIN DRUG
		WHERE SPECIALTY_DESCRIPTION = 'Pain Management'
			AND NPPES_PROVIDER_CITY = 'NASHVILLE'
			AND OPIOID_DRUG_FLAG = 'Y') AS SUBQUERY
LEFT JOIN PRESCRIPTION USING (NPI, DRUG_NAME)
ORDER BY TOTAL_CLAIM_COUNT DESC;

--- Part 2
-- Question 1
SELECT
	(SELECT COUNT(DISTINCT NPI) AS NPI_COUNT
		FROM PRESCRIBER) -
	(SELECT COUNT(DISTINCT NPI) AS NPI_COUNT
		FROM PRESCRIPTION) AS NPI_DIFFERENCE 
/* Answer: There are 4458 NPIs that appear in the prescriber table but not
in the prescription table.*/ 

-- Question 2a
SELECT DRUG.GENERIC_NAME,
	SUM(TOTAL_CLAIM_COUNT) AS TOTAL_COUNT
FROM PRESCRIBER
INNER JOIN PRESCRIPTION USING (NPI)
INNER JOIN DRUG USING(DRUG_NAME)
WHERE SPECIALTY_DESCRIPTION = 'Family Practice'
GROUP BY GENERIC_NAME
ORDER BY TOTAL_COUNT DESC
LIMIT 5;
-- Answer: See genereated table.

-- Question 2b
SELECT DRUG.GENERIC_NAME,
	SUM(TOTAL_CLAIM_COUNT) AS TOTAL_COUNT
FROM PRESCRIBER
INNER JOIN PRESCRIPTION USING (NPI)
INNER JOIN DRUG USING(DRUG_NAME)
WHERE SPECIALTY_DESCRIPTION = 'Cardiology'
GROUP BY GENERIC_NAME
ORDER BY TOTAL_COUNT DESC
LIMIT 5;
-- Answer: See genereated table.

-- Question 2c
WITH FAMILY_PRACTICE AS
	(SELECT GENERIC_NAME,
			SUM(TOTAL_CLAIM_COUNT) AS TOTAL_COUNT
		FROM PRESCRIBER
		INNER JOIN PRESCRIPTION USING (NPI)
		INNER JOIN DRUG USING(DRUG_NAME)
		WHERE SPECIALTY_DESCRIPTION = 'Family Practice'
		GROUP BY GENERIC_NAME
		ORDER BY TOTAL_COUNT DESC
		LIMIT 5),
	CARDIOLOGY AS
	(SELECT GENERIC_NAME,
			SUM(TOTAL_CLAIM_COUNT) AS TOTAL_COUNT
		FROM PRESCRIBER
		INNER JOIN PRESCRIPTION USING (NPI)
		INNER JOIN DRUG USING(DRUG_NAME)
		WHERE SPECIALTY_DESCRIPTION = 'Cardiology'
		GROUP BY GENERIC_NAME
		ORDER BY TOTAL_COUNT DESC
		LIMIT 5)
SELECT GENERIC_NAME
FROM FAMILY_PRACTICE INTERSECT
SELECT GENERIC_NAME
FROM CARDIOLOGY;
-- Answer: Atorvastatin Calcium and Amplodipine Besylate are contained in both queries.

-- Question 3a
SELECT DISTINCT NPI,
	NPPES_PROVIDER_CITY AS CITY,
	SUM(TOTAL_CLAIM_COUNT) AS TOTAL_CLAIMS
FROM PRESCRIBER
INNER JOIN PRESCRIPTION USING (NPI)
WHERE NPPES_PROVIDER_CITY = 'NASHVILLE'
GROUP BY NPI,
	NPPES_PROVIDER_CITY
ORDER BY TOTAL_CLAIMS DESC
LIMIT 5;

-- Question 3b
SELECT DISTINCT NPI,
	NPPES_PROVIDER_CITY AS CITY,
	SUM(TOTAL_CLAIM_COUNT) AS TOTAL_CLAIMS
FROM PRESCRIBER
INNER JOIN PRESCRIPTION USING (NPI)
WHERE NPPES_PROVIDER_CITY = 'MEMPHIS'
GROUP BY NPI,
	NPPES_PROVIDER_CITY
LIMIT 5;

-- Question 3c
WITH NASHVILLE AS
	(SELECT DISTINCT NPI,
			NPPES_PROVIDER_CITY AS CITY,
			SUM(TOTAL_CLAIM_COUNT) AS TOTAL_CLAIMS
		FROM PRESCRIBER
		INNER JOIN PRESCRIPTION USING (NPI)
		WHERE NPPES_PROVIDER_CITY = 'NASHVILLE'
		GROUP BY NPI,
			NPPES_PROVIDER_CITY
		LIMIT 5),
	MEMPHIS AS
	(SELECT DISTINCT NPI,
			NPPES_PROVIDER_CITY AS CITY,
			SUM(TOTAL_CLAIM_COUNT) AS TOTAL_CLAIMS
		FROM PRESCRIBER
		INNER JOIN PRESCRIPTION USING (NPI)
		WHERE NPPES_PROVIDER_CITY = 'MEMPHIS'
		GROUP BY NPI,
			NPPES_PROVIDER_CITY
		LIMIT 5),
	KNOXVILLE AS
	(SELECT DISTINCT NPI,
			NPPES_PROVIDER_CITY AS CITY,
			SUM(TOTAL_CLAIM_COUNT) AS TOTAL_CLAIMS
		FROM PRESCRIBER
		INNER JOIN PRESCRIPTION USING (NPI)
		WHERE NPPES_PROVIDER_CITY = 'KNOXVILLE'
		GROUP BY NPI,
			NPPES_PROVIDER_CITY
		LIMIT 5),
	CHATTANOOGA AS
	(SELECT DISTINCT NPI,
			NPPES_PROVIDER_CITY AS CITY,
			SUM(TOTAL_CLAIM_COUNT) AS TOTAL_CLAIMS
		FROM PRESCRIBER
		INNER JOIN PRESCRIPTION USING (NPI)
		WHERE NPPES_PROVIDER_CITY = 'CHATTANOOGA'
		GROUP BY NPI,
			NPPES_PROVIDER_CITY
		LIMIT 5)
SELECT *
FROM NASHVILLE
UNION
SELECT *
FROM MEMPHIS
UNION
SELECT *
FROM KNOXVILLE
UNION
SELECT *
FROM CHATTANOOGA
ORDER BY CITY,
	TOTAL_CLAIMS DESC;

-- Question 4
SELECT COUNTY,
	OVERDOSE_DEATHS
FROM FIPS_COUNTY
INNER JOIN OVERDOSE_DEATHS USING (FIPSCOUNTY)
WHERE YEAR = 2017
	AND OVERDOSE_DEATHS >
		(SELECT AVG(OVERDOSE_DEATHS)
			FROM OVERDOSE_DEATHS
			WHERE YEAR = 2017)
ORDER BY OVERDOSE_DEATHS DESC;

-- Question 5a
SELECT SUM(POPULATION) AS TOTAL_TENNESSEE_POPULATION
FROM POPULATION;
-- The total population of Tennessee is 6,597,381.

-- Question 5b
SELECT COUNTY,
	POPULATION,
	ROUND(POPULATION * 100 / (SELECT SUM(POPULATION)
									FROM POPULATION), 2) AS POPULATION_PERCENTAGE
FROM FIPS_COUNTY
INNER JOIN POPULATION USING (FIPSCOUNTY)
ORDER BY POPULATION_PERCENTAGE DESC;